language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: make install
script: make test
env:
  global:
  - secure: HDBNxdK0TlUeIYVoUzVuUX0XrwhP+NpzGWIBK76u8EgOvDWWoh1XO6DVvYQ7k1KXAtbgrevQ79U/5+zx+AplTE+6JiL3Fjib1P8OGerIjCKe1rrW/ndhbRUuM//CxPwHhE9q/96eUHNkvTP6xIZZRx1z3Deye++R/sAaT77xOPU=
